<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class UsCity extends Model
{
    protected $fillable = [
        'city',
        'city_ascii',
        'city_alt',
        'state_id',
        'state_name',
        'county_fips',
        'county_name',
        'county_fips_all',
        'county_name_all',
        'lat',
        'lng',
        'population',
        'population_proper',
        'density',
        'source',
        'military',
        'incorporated',
        'cdp',
        'timezone',
        'ranking',
        'zips',
        'simplemaps_id',
        'age_median',
        'male',
        'female',
        'married',
        'family_size',
        'income_household_median',
        'income_household_six_figure',
        'home_ownership',
        'home_value',
        'rent_median',
        'education_college_or_above',
        'labor_force_participation',
        'unemployment_rate',
        'race_white',
        'race_black',
        'race_asian',
        'race_native',
        'race_pacific',
        'race_other',
        'race_multiple',
    ];

    protected $casts = [
        'lat' => 'decimal:6',
        'lng' => 'decimal:6',
        'population' => 'integer',
        'population_proper' => 'integer',
        'density' => 'decimal:2',
        'military' => 'boolean',
        'incorporated' => 'boolean',
        'cdp' => 'boolean',
        'ranking' => 'integer',
        'age_median' => 'decimal:2',
        'male' => 'decimal:2',
        'female' => 'decimal:2',
        'married' => 'decimal:2',
        'family_size' => 'decimal:2',
        'income_household_median' => 'integer',
        'income_household_six_figure' => 'decimal:2',
        'home_ownership' => 'decimal:2',
        'home_value' => 'integer',
        'rent_median' => 'integer',
        'education_college_or_above' => 'decimal:2',
        'labor_force_participation' => 'decimal:2',
        'unemployment_rate' => 'decimal:2',
        'race_white' => 'decimal:2',
        'race_black' => 'decimal:2',
        'race_asian' => 'decimal:2',
        'race_native' => 'decimal:2',
        'race_pacific' => 'decimal:2',
        'race_other' => 'decimal:2',
        'race_multiple' => 'decimal:2',
    ];
}
